# Generated by Django 4.2.4 on 2023-08-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('B', 'billing_address'), ('S', 'Shipping_address')], max_length=1),
        ),
    ]
