# Generated by Django 4.2.4 on 2024-02-08 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop', '0009_alter_wishlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapatransaction',
            name='email',
            field=models.EmailField(default='sami', max_length=254),
        ),
        migrations.AddField(
            model_name='chapatransaction',
            name='first_name',
            field=models.CharField(default='sami', max_length=100),
        ),
        migrations.AddField(
            model_name='chapatransaction',
            name='last_name',
            field=models.CharField(default='sami', max_length=100),
        ),
        migrations.AddField(
            model_name='chapatransaction',
            name='return_url',
            field=models.URLField(default='sami'),
        ),
        migrations.AddField(
            model_name='chapatransaction',
            name='tx_ref',
            field=models.CharField(default='sami', max_length=100),
        ),
        migrations.AddField(
            model_name='chapatransaction',
            name='username',
            field=models.CharField(default='sami', max_length=100),
        ),
        migrations.AlterField(
            model_name='chapatransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=190, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chapatransaction',
            name='currency',
            field=models.CharField(default='ETB', max_length=10),
        ),
        migrations.AlterField(
            model_name='chapatransaction',
            name='user',
            field=models.ForeignKey(default='sami', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
