# Generated by Django 4.1.4 on 2024-02-23 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0011_alter_chapatransaction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapatransaction',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='eshop.chapatransaction'),
        ),
    ]
