# Generated by Django 4.2.4 on 2023-08-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_alter_address_address1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
