# Generated by Django 4.2.4 on 2024-02-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0010_chapatransaction_email_chapatransaction_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapatransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chapatransaction',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='chapatransaction',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chapatransaction',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chapatransaction',
            name='return_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='chapatransaction',
            name='tx_ref',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chapatransaction',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
